# Site settings
title: marcusoft.net - sharing is learning
email: marcusoftnet@gmail.com
description: "The blog of Marcus Hammarberg - stuff i picked up along the way"
baseurl: ""
url: "http://www.marcusoft.net"
twitter_username: marcusoftnet
github_username:  marcusoftnet

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title.html
paginate: 10
exclude: [
	"node_modules",
	"import",
	"gemfile",
	"gemfile.lock",
	"package.json",
	"CNAME",
	"README.md",
	"LICENSE",
	"Gruntfile.js",
	".gitignore",
	"kanban.txt"
]
