# Site settings
title: marcusoft.net - sharing is learning
email: your-email@yourdomain.com
description: "The blog of Marcus Hammarberg - stuff i picked up along the way"
baseurl: ""
url: "http://www.marcusoft.net"
twitter_username: marcusoftnet
github_username:  marcusoftnet

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["node_modules"]
