# Site settings
title: marcusoft.net - sharing is learning
author_name: Marcus Hammarberg
email: marcusoftnet@gmail.com
description: "Marcus Hammarberg - my thoughts on lean, agile, kanban, nodejs, nancyfx, koa and other things makes me learn faster"
baseurl: ""
url: "http://www.marcusoft.net"
twitter_username: marcusoftnet
github_username:  marcusoftnet
disqus_shortname:  marcusoftnet
excerpt_separator: <a name='more'></a> # http://snippetrepo.com/snippets/customized-excerpt-separator-in-jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
permalink: /:year/:month/:title.html
timezone: Europe/Stockholm
incremental: false
paginate: 20
exclude: [
	"node_modules",
	"import",
	"gemfile",
	"gemfile.lock",
	"package.json",
	"CNAME",
	"README.md",
	"LICENSE",
	"Gruntfile.js",
	".gitignore",
	"scaffold_post",
	"start_local"
]
gems: ["jekyll-paginate", "classifier-reborn", "gsl"]
