# Site settings
title: marcusoft.net - sharing is learning
author_name: Marcus Hammarberg
email: marcusoftnet@gmail.com
description: "The blog of Marcus Hammarberg - stuff i picked up along the way"
baseurl: ""
url: "http://www.marcusoft.net"
twitter_username: marcusoftnet
github_username:  marcusoftnet
disqus_shortname:  marcusoftnet
excerpt_separator: <a name='more'></a> # http://snippetrepo.com/snippets/customized-excerpt-separator-in-jekyll

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title.html
paginate: 10
exclude: [
	"node_modules",
	"import",
	"gemfile",
	"gemfile.lock",
	"package.json",
	"CNAME",
	"README.md",
	"LICENSE",
	"Gruntfile.js",
	".gitignore",
	"kanban.txt",
	"scaffold_post"
]
